service: elements-of-programming-interviews

provider:
  name: aws
  runtime: python3.8
  stage: dev # used by default
  region: us-east-1

functions:
  elements-of-programming-interviews:
    name: elements-of-programming-interviews
    handler: source/main.lambda_handler
    timeout: 300 # seconds
    memorySize: 128 # mb