name: Main Workflow

# This workflow executes when pushing to main branch.
on: 
  push:
    branches:
      - main

# todo: add caching. Shouldn't have to re-download serverless every time.
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Deploy to AWS Lambda
        # This action wraps all serverless CLI commands.
        # Will run from root directory where serverless.yml is located.
        # Removes the need to download serverless to host runner. 
        # https://github.com/serverless/github-action
        uses: serverless/github-action@master
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}